//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaF___PvP_Installer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AttackAnimation {
            get {
                return ((int)(this["AttackAnimation"]));
            }
            set {
                this["AttackAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PauseBaseGame {
            get {
                return ((int)(this["PauseBaseGame"]));
            }
            set {
                this["PauseBaseGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsePokemonGifs {
            get {
                return ((int)(this["UsePokemonGifs"]));
            }
            set {
                this["UsePokemonGifs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShowAttackTypes {
            get {
                return ((int)(this["ShowAttackTypes"]));
            }
            set {
                this["ShowAttackTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShowAttacks {
            get {
                return ((int)(this["ShowAttacks"]));
            }
            set {
                this["ShowAttacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LowSpecMode {
            get {
                return ((int)(this["LowSpecMode"]));
            }
            set {
                this["LowSpecMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllowLegendarys {
            get {
                return ((int)(this["AllowLegendarys"]));
            }
            set {
                this["AllowLegendarys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChampShuffle {
            get {
                return ((int)(this["ChampShuffle"]));
            }
            set {
                this["ChampShuffle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DoSwitch {
            get {
                return ((int)(this["DoSwitch"]));
            }
            set {
                this["DoSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaF - PvP Scene")]
        public string SwitchName {
            get {
                return ((string)(this["SwitchName"]));
            }
            set {
                this["SwitchName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PokemonSizeModifier {
            get {
                return ((string)(this["PokemonSizeModifier"]));
            }
            set {
                this["PokemonSizeModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LimitPvPScenes {
            get {
                return ((int)(this["LimitPvPScenes"]));
            }
            set {
                this["LimitPvPScenes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaF - PvP Scene")]
        public string AllowedScenes {
            get {
                return ((string)(this["AllowedScenes"]));
            }
            set {
                this["AllowedScenes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FixedCoordinates {
            get {
                return ((int)(this["FixedCoordinates"]));
            }
            set {
                this["FixedCoordinates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public string AttackpowerMin {
            get {
                return ((string)(this["AttackpowerMin"]));
            }
            set {
                this["AttackpowerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string AttackpowerMax {
            get {
                return ((string)(this["AttackpowerMax"]));
            }
            set {
                this["AttackpowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string AttackIncrease {
            get {
                return ((string)(this["AttackIncrease"]));
            }
            set {
                this["AttackIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string CritChance {
            get {
                return ((string)(this["CritChance"]));
            }
            set {
                this["CritChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string DodgeChance {
            get {
                return ((string)(this["DodgeChance"]));
            }
            set {
                this["DodgeChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string SturdyChance {
            get {
                return ((string)(this["SturdyChance"]));
            }
            set {
                this["SturdyChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public string ChallengeTimer {
            get {
                return ((string)(this["ChallengeTimer"]));
            }
            set {
                this["ChallengeTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string CooldownTimer {
            get {
                return ((string)(this["CooldownTimer"]));
            }
            set {
                this["CooldownTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Challenge the Champ")]
        public string Champ {
            get {
                return ((string)(this["Champ"]));
            }
            set {
                this["Champ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string PriceChamp {
            get {
                return ((string)(this["PriceChamp"]));
            }
            set {
                this["PriceChamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseChamp {
            get {
                return ((int)(this["UseChamp"]));
            }
            set {
                this["UseChamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Normal 3vs3")]
        public string Normal3v3 {
            get {
                return ((string)(this["Normal3v3"]));
            }
            set {
                this["Normal3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string PriceNormal3v3 {
            get {
                return ((string)(this["PriceNormal3v3"]));
            }
            set {
                this["PriceNormal3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseNormal3v3 {
            get {
                return ((int)(this["UseNormal3v3"]));
            }
            set {
                this["UseNormal3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Normal 6vs6")]
        public string Normal6v6 {
            get {
                return ((string)(this["Normal6v6"]));
            }
            set {
                this["Normal6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PriceNormal6v6 {
            get {
                return ((string)(this["PriceNormal6v6"]));
            }
            set {
                this["PriceNormal6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseNormal6v6 {
            get {
                return ((int)(this["UseNormal6v6"]));
            }
            set {
                this["UseNormal6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Random 3vs3")]
        public string Random3v3 {
            get {
                return ((string)(this["Random3v3"]));
            }
            set {
                this["Random3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string PriceRandom3v3 {
            get {
                return ((string)(this["PriceRandom3v3"]));
            }
            set {
                this["PriceRandom3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRandom3v3 {
            get {
                return ((int)(this["UseRandom3v3"]));
            }
            set {
                this["UseRandom3v3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Random 6vs6")]
        public string Random6v6 {
            get {
                return ((string)(this["Random6v6"]));
            }
            set {
                this["Random6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PriceRandom6v6 {
            get {
                return ((string)(this["PriceRandom6v6"]));
            }
            set {
                this["PriceRandom6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRandom6v6 {
            get {
                return ((int)(this["UseRandom6v6"]));
            }
            set {
                this["UseRandom6v6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAMMILocation {
            get {
                return ((string)(this["SAMMILocation"]));
            }
            set {
                this["SAMMILocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PvP - Challenge a region")]
        public string Region {
            get {
                return ((string)(this["Region"]));
            }
            set {
                this["Region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PriceRegion {
            get {
                return ((string)(this["PriceRegion"]));
            }
            set {
                this["PriceRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRegion {
            get {
                return ((int)(this["UseRegion"]));
            }
            set {
                this["UseRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string BonusChamp {
            get {
                return ((string)(this["BonusChamp"]));
            }
            set {
                this["BonusChamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AbsoluteSpeed {
            get {
                return ((int)(this["AbsoluteSpeed"]));
            }
            set {
                this["AbsoluteSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LegendaryCount {
            get {
                return ((string)(this["LegendaryCount"]));
            }
            set {
                this["LegendaryCount"] = value;
            }
        }
    }
}
